'use client';

import React, { useState } from 'react';
import { PlaceCandidate } from '../domain/types';
import {
  Calendar,
  Clock,
  MapPin,
  Trash2,
  Share2,
  Copy,
  Check,
  X,
  Sparkles,
  ArrowRight,
  Sun,
  Moon,
  Compass
} from 'lucide-react';
import styles from './ItineraryModal.module.css';

interface ItineraryModalProps {
  isOpen: boolean;
  onClose: () => void;
  savedPlaces: PlaceCandidate[];
  onRemovePlace: (placeId: string) => void;
  userLocation: string;
  onSelectPlace: (place: PlaceCandidate) => void;
}

export const ItineraryModal: React.FC<ItineraryModalProps> = ({
  isOpen,
  onClose,
  savedPlaces,
  onRemovePlace,
  userLocation,
  onSelectPlace,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const totalDistance = savedPlaces.reduce((sum, p) => sum + p.distanceKm, 0);
  const totalDriveTime = savedPlaces.reduce((sum, p) => sum + p.travelTimeMinutes, 0);

  const handleCopyItinerary = () => {
    if (savedPlaces.length === 0) return;

    const lines = [
      `🌟 Aura — My Custom Trip Plan (${userLocation})`,
      `=========================================`,
      ...savedPlaces.map((p, idx) => {
        return `\n${idx + 1}. ${p.name} (${p.category})
📍 ${p.address} (${p.distanceKm} km · ~${p.travelTimeMinutes} min from ${userLocation})
⭐ Rating: ${p.reviewSummary.rating}/5 (${p.reviewSummary.reviewCount} reviews)
🎯 Match: ${p.intentMatch.score}% - ${p.intentMatch.explanation}
🌊 Activities: ${p.activities.join(', ')}
🛏 Stay: ${p.accommodation.available ? p.accommodation.type : 'Day visit only'}`;
      }),
      `\n=========================================`,
      `Generated by Aura AI Local Discovery Agent`,
    ];

    navigator.clipboard.writeText(lines.join('\n'));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className={styles.modalOverlay} onClick={onClose}>
      <div className={styles.modalContainer} onClick={(e) => e.stopPropagation()}>
        <div className={styles.header}>
          <div className={styles.titleGroup}>
            <div className={styles.titleIcon}>
              <Calendar size={20} color="#e6a756" />
            </div>
            <div>
              <h2 className={styles.title}>Your Custom Trip Itinerary</h2>
              <p className={styles.subtitle}>
                AI synthesized schedule & route starting from {userLocation}
              </p>
            </div>
          </div>

          <button className={styles.closeBtn} onClick={onClose} aria-label="Close modal">
            <X size={20} />
          </button>
        </div>

        {savedPlaces.length === 0 ? (
          <div className={styles.emptyState}>
            <div className={styles.emptyIcon}>
              <Compass size={40} color="#64748b" />
            </div>
            <h3>No venues added to your trip yet</h3>
            <p>
              Browse verified places and click <strong>&quot;Save to Trip&quot;</strong> to build your personalized weekend itinerary.
            </p>
          </div>
        ) : (
          <div className={styles.content}>
            {/* Trip Stats Bar */}
            <div className={styles.statsBar}>
              <div className={styles.statItem}>
                <span className={styles.statLabel}>Saved Places</span>
                <span className={styles.statValue}>{savedPlaces.length} venues</span>
              </div>
              <div className={styles.statDivider} />
              <div className={styles.statItem}>
                <span className={styles.statLabel}>Est. Total Distance</span>
                <span className={styles.statValue}>{totalDistance.toFixed(1)} km</span>
              </div>
              <div className={styles.statDivider} />
              <div className={styles.statItem}>
                <span className={styles.statLabel}>Total Drive Time</span>
                <span className={styles.statValue}>~{totalDriveTime} min</span>
              </div>
            </div>

            {/* Timeline Schedule */}
            <div className={styles.timelineSection}>
              <h3 className={styles.timelineTitle}>
                <Sparkles size={16} color="#38bdf8" />
                <span>Recommended Weekend Timeline</span>
              </h3>

              <div className={styles.timelineList}>
                {savedPlaces.map((place, idx) => {
                  const isFirst = idx === 0;
                  const timeSlot = isFirst ? '14:30 — Afternoon' : '19:30 — Sunset & Evening';
                  const Icon = isFirst ? Sun : Moon;

                  return (
                    <div key={place.id} className={styles.timelineItem}>
                      <div className={styles.timelineMarker}>
                        <Icon size={16} color="#e6a756" />
                        {idx < savedPlaces.length - 1 && <div className={styles.timelineLine} />}
                      </div>

                      <div className={styles.timelineCard}>
                        <div className={styles.cardHeader}>
                          <div>
                            <span className={styles.timeBadge}>{timeSlot}</span>
                            <h4
                              className={styles.placeName}
                              onClick={() => {
                                onSelectPlace(place);
                                onClose();
                              }}
                            >
                              {place.name}
                            </h4>
                          </div>

                          <button
                            className={styles.removeBtn}
                            onClick={() => onRemovePlace(place.id)}
                            title="Remove from trip"
                          >
                            <Trash2 size={15} />
                          </button>
                        </div>

                        <div className={styles.cardMeta}>
                          <span>📍 {place.distanceKm} km · ~{place.travelTimeMinutes} min</span>
                          <span>•</span>
                          <span>⭐ {place.reviewSummary.rating} ({place.reviewSummary.reviewCount} reviews)</span>
                        </div>

                        <p className={styles.cardWhy}>
                          ✓ {place.intentMatch.explanation}
                        </p>

                        <div className={styles.cardTags}>
                          {place.activities.map((act, i) => (
                            <span key={i} className={styles.cardTag}>{act}</span>
                          ))}
                          {place.accommodation.available && (
                            <span className={`${styles.cardTag} ${styles.stayTag}`}>
                              🛏 {place.accommodation.type}
                            </span>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        )}

        {/* Footer Actions */}
        <div className={styles.footer}>
          <button className={styles.secondaryBtn} onClick={onClose}>
            Close
          </button>

          {savedPlaces.length > 0 && (
            <button className={styles.primaryBtn} onClick={handleCopyItinerary}>
              {copied ? (
                <>
                  <Check size={16} color="#0b1320" />
                  <span>Copied to Clipboard!</span>
                </>
              ) : (
                <>
                  <Copy size={16} />
                  <span>Copy Trip Summary</span>
                </>
              )}
            </button>
          )}
        </div>
      </div>
    </div>
  );
};
